# Inline smart switch

<<: !include esp_modules/tywe2s.yaml
<<: !include common/status_led.yaml

substitutions:
  status_led_pin: GPIO13
  restore_mode: ALWAYS_ON

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO1
      mode: INPUT_PULLUP
      inverted: true
    name: "${node_name_upper} Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "${node_name_upper} Status"

switch:
  - platform: gpio
    name: "${node_name_upper}"
    pin: GPIO14
    id: relay
    restore_mode: ${restore_mode}
