# 2 way smart switch

<<: !include esp_modules/tywe3s.yaml
<<: !include common/status_led.yaml

substitutions:
  status_led_pin: GPIO4
  left_name: "Left"
  left_restore_mode: ALWAYS_OFF
  left_icon: "mdi:lightbulb"
  right_name: "Right"
  right_restore_mode: ALWAYS_OFF
  right_icon: "mdi:lightbulb"

binary_sensor:
- platform: gpio
  pin:
    number: GPIO16
    inverted: true
  name: "${left_name} Button"
  on_press:
    - light.toggle: relay_left
- platform: gpio
  pin:
    number: GPIO12
    inverted: true
  name: "${right_name} Button"
  on_press:
    - light.toggle: relay_right
- platform: status
  name: "${node_name_upper} Status"

light:
- platform: binary
  name: ${left_name}
  icon: ${left_icon}
  output: light_output_left
  id: relay_left
  restore_mode: ${left_restore_mode}
- platform: binary
  name: ${right_name}
  icon: ${right_icon}
  output: light_output_right
  id: relay_right
  restore_mode: ${right_restore_mode}

output:
- platform: gpio
  pin: GPIO13
  id: light_output_left
- platform: gpio
  pin: GPIO14
  id: light_output_right
