<<: !include esp_modules/esp12s.yaml
<<: !include common/link_led.yaml

substitutions:
  link_led_pin: GPIO4

binary_sensor:
- platform: gpio
  pin:
    number: GPIO16
    inverted: true
  name: "Left Button"
  on_press:
    - switch.toggle: relay_left
- platform: gpio
  pin:
    number: GPIO12
    inverted: true
  name: "Right Button"
  on_press:
    - switch.toggle: relay_right
- platform: status
  name: "Status"

switch:
- platform: gpio
  name: "Left Outlet"
  pin: GPIO13
  id: relay_left
- platform: gpio
  name: "Right Outlet"
  pin: GPIO14
  id: relay_right
