# Smart outlet

<<: !include esp_modules/tywe3s.yaml
<<: !include common/status_led.yaml

substitutions:
  status_led_pin: GPIO4
  left_name: "Left"
  right_name: "Right"

binary_sensor:
- platform: gpio
  pin:
    number: GPIO16
    inverted: true
  name: "${left_name} Button"
  on_press:
    - light.toggle: relay_left
- platform: gpio
  pin:
    number: GPIO12
    inverted: true
  name: "${right_name} Button"
  on_press:
    - light.toggle: relay_right
- platform: status
  name: "${node_name_upper} Status"

switch:
- platform: binary
  name: ${left_name}
  output: light_output_left
  id: relay_left
- platform: binary
  name: ${right_name}
  output: light_output_right
  id: relay_right

output:
- platform: gpio
  pin: GPIO13
  id: light_output_left
- platform: gpio
  pin: GPIO14
  id: light_output_right
