# Smart outlet
# The 6294 requires a module replacements, I have listed the tywe2s as the module as that is what I had the day I needed to make this work

<<: !include esp_modules/tywe2s.yaml
<<: !include common/status_led.yaml
<<: !include common/deta_power_meter.yaml

substitutions:
  status_led_pin: GPIO5
  left_name: "Left"
  left_restore_mode: ALWAYS_ON
  right_name: "Right"
  right_restore_mode: ALWAYS_ON
  update_interval: 60s

binary_sensor:
- platform: gpio
  pin:
    number: GPIO4
    inverted: true
    mode:
      input: true
      pullup: true
  name: "${left_name} Button"
  on_press:
    - switch.toggle: relay_left
- platform: gpio
  pin:
    number: GPIO12
    inverted: true
    mode:
      input: true
      pullup: true
  name: "${right_name} Button"
  on_press:
    - switch.toggle: relay_right
- platform: status
  name: "${node_name_upper} Status"

switch:
- platform: gpio
  name: ${left_name}
  pin: GPIO13
  id: relay_left
  restore_mode: ${left_restore_mode}
- platform: gpio
  name: ${right_name}
  pin: GPIO14
  id: relay_right
  restore_mode: ${right_restore_mode}
