<<: !include esp_modules/tywe2s.yaml
<<: !include common/link_led.yaml

substitutions:
  link_led_pin: GPIO13

binary_sensor:
- platform: gpio
  pin:
    number: GPIO1
    mode: INPUT_PULLUP
    inverted: true
  name: "Button"
  on_press:
    - switch.toggle: relay
- platform: status
  name: "Status"

switch:
- platform: gpio
  name: "Switch"
  pin: GPIO14
  id: relay
