# Single smart switch

<<: !include esp_modules/tywe3s.yaml
<<: !include common/status_led.yaml

substitutions:
  status_led_pin: GPIO4

binary_sensor:
- platform: gpio
  pin:
    number: GPIO16
    inverted: true
  name: "${node_name_upper} Button"
  on_press:
    - switch.toggle: relay
- platform: status
  name: "${node_name_upper} Status"

switch:
- platform: gpio
  name: ${node_name_upper}
  pin: GPIO13
  id: relay

output:
- platform: esp8266_pwm
  id: status_led
  pin: GPIO4
  inverted: true
