# Single smart switch

<<: !include esp_modules/tywe3s.yaml
<<: !include common/status_led.yaml

substitutions:
  status_led_pin: GPIO4
  restore_mode: ALWAYS_OFF
  icon: "mdi:lightbulb"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      inverted: true
    name: "${node_name_upper} Button"
    on_press:
      - light.toggle: relay
  - platform: status
    name: "${node_name_upper} Status"

light:
  - platform: binary
    name: ${node_name_upper}
    icon: ${icon}
    output: light_output
    id: relay
    restore_mode: ${restore_mode}

output:
  - platform: gpio
    pin: GPIO13
    id: light_output
