# Sonoff smart plug

<<: !include common/status_led.yaml

substitutions:
  status_led_pin: GPIO13
  icon: "mdi:lightbulb"

esphome:
  name: ${node_name}
  platform: ESP8266
  board: sonoff_s20

binary_sensor:
- platform: gpio
  pin:
    number: GPIO0
    mode: INPUT_PULLUP
    inverted: true
  name: "${node_name_upper} Button"
  on_press:
    - light.toggle: relay
- platform: status
  name: "${node_name_upper} Status"

light:
- platform: binary
  name: ${node_name_upper}
  icon: ${icon}
  output: light_output
  id: relay

output:
- platform: gpio
  pin: GPIO12
  id: light_output
