# Sonoff smart plug

!include common/link_led.yaml

substitutions:
  link_led_pin: GPIO13

esphome:
  name: ${node_name}
  platform: ESP8266
  board: sonoff_s20

binary_sensor:
- platform: gpio
  pin:
    number: GPIO0
    mode: INPUT_PULLUP
    inverted: true
  name: "${node_name_upper} Button"
  on_press:
    - switch.toggle: relay
- platform: status
  name: "${node_name_upper} Status"

switch:
- platform: gpio
  name: "${node_name_upper}"
  pin: GPIO12
  id: relay
